[general]
import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[font]
size = 14
normal = { family = "JetBrainsMono Nerd Font Mono", style="Regular" }

[window]
# padding = { x = 10, y = 30 }
padding = { x = 10, y = 10 }
# opacity = 0.9
# blur = false
# decorations = "Transparent"
decorations = "Buttonless"

# [keyboard]
# bindings = [
#   { key = "T", mods = "Command", action = "CreateNewTab" }
# ]
